### ISSUE TITLE
showcase images not resizing on mobile

### ISSUE THREAD

**Issue by yellowtailfan** [StartBootstrap/startbootstrap-landing-page#81]
The showcase images work well on desktop for different browser window sizes. But on mobile, the showcase images are very heavily cropped (e.g. showing maybe 20% of the image). This is on iOS 13 and recent version of Android.

**Comment by davidtmiller** [comment]
They are set as background images in order to preserve the height of the container so it lines up with the text areas to the sides. You could go in and remove this behavior as a preference though!
