### ISSUE TITLE
How to create a second page

### ISSUE THREAD

**Issue by w4rner** [StartBootstrap/startbootstrap-landing-page#82]
As you can see, I've got a front page up live at agileEducation.co. 
I'm looking to now create a page at agileEducation.co/nlrp (redirect from nlrp.tech). How should I go about this?

**Comment by w4rner** [comment]
@blackrockDigital any ideas on this?

**Comment by w4rner** [comment]
Just created a file called nlrp.html. I used the original index.html as a template. I just created a custom link between the pages.
have y'all created a more specific framework for this though?

**Comment by davidtmiller** [comment]
You can simply add a new page to your root directory next to `index.html` and link to it from wherever you want in the file. Since this is just raw HTML there is nothing too special about it!
