### ISSUE TITLE
Heroku Deployment not working

### ISSUE THREAD

**Issue by angelina-tsuboi** [StartBootstrap/startbootstrap-landing-page#99]
When I try to deploy my website onto heroku using [this tutorial](https://blog.teamtreehouse.com/deploy-static-site-heroku) it is not working. It returns the following error:
```
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '"/Applications/Visual'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:945:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:363:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:61:3)
    at internal/main/run_main_module.js:11:1
```

**Comment by airobot60** [comment]
> When I try to deploy my website onto heroku using [this tutorial](https://blog.teamtreehouse.com/deploy-static-site-heroku) it is not working. It returns the following error:
> 
> ```
> 
> internal/modules/cjs/loader.js:670
> 
>     throw err;
> 
>     ^
> 
> 
> 
> Error: Cannot find module '"/Applications/Visual'
> 
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:591:27)
> 
>     at Module.require (internal/modules/cjs/loader.js:723:19)
> 
>     at Module._preloadModules (internal/modules/cjs/loader.js:945:12)
> 
>     at loadPreloadModules (internal/bootstrap/pre_execution.js:363:5)
> 
>     at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:61:3)
> 
>     at internal/main/run_main_module.js:11:1
> 
> ```

**Comment by davidtmiller** [comment]
Since this isn't an issue with this theme, rather a usage choice, it isn't related I'm afraid.
